### ISSUE TITLE
Feature request: specify your own docker base-image

### ISSUE THREAD

**Issue by chiefy** [VictorBjelkholm/autochecker#1]
I love Alpine, but if anything in `node_modules` needs rebuilt, you will have to figure out what `apk` to add. Would be awesome to be able to specify your own base image (and repo) pull in `package.json`:

```
...
"autochecker": {
  "repo-host": "https://quay.io",
  "base-image": "someuser/nodejs"
}
...
```

awesome project btw!

**Comment by VictorBjelkholm** [comment]
As I see it, PR #2 would fix this, because you could provide your own Dockerfile :)

Maybe this way would be easier and simpler, but providing a Dockerfile I think is simple enough.

Thanks for the idea 👍
